openapi: "3.0.1"
info:
  title: "Audits API"
  version: "0.0.1"
paths:
  /audits:
    get:
      responses:
        default:
          description: "GET /audits"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaAPIAuditsIndex.Arn}/invocations
        connectionType: "INTERNET"
    post:
      responses:
        default:
          description: "POST /audits"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaAPIAuditsCreate.Arn}/invocations
        connectionType: "INTERNET"
  /audits/{audit}:
    get:
      responses:
        default:
          description: "GET /audits/{audit}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaAPIAuditsShow.Arn}/invocations
        connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
    - "GET"
    - "HEAD"
    - "OPTIONS"
    - "POST"
  allowOrigins:
    - "*"
