AWSTemplateFormatVersion: 2010-09-09

Description: A Serverless API for storing PageSpeed Insight reports

Resources:
  BucketAudits:
    Type: "AWS::S3::Bucket"
    DependsOn:
      - RoleAudits

  LambdaAPIAuditsCreate:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: POST /audits
      Code: ../dist/API_Audits_Create
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 120
      Role: !GetAtt RoleAudits.Arn
      Environment:
        Variables:
          AUDITS_BUCKET: !Ref BucketAudits
          AUDITS_TABLE: !Ref DynamoTableAudits

  LambdaAPIAuditsIndex:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: GET /audits
      Code: ../dist/API_Audits_Index
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 5
      Role: !GetAtt RoleAudits.Arn
      Environment:
        Variables:
          AUDITS_TABLE: !Ref DynamoTableAudits

  LambdaAPIAuditsShow:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: GET /audits/:audit
      Code: ../dist/API_Audits_Show
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 5
      Role: !GetAtt RoleAudits.Arn
      Environment:
        Variables:
          AUDITS_BUCKET: !Ref BucketAudits
          AUDITS_TABLE: !Ref DynamoTableAudits

  LambdaStreamAuditsDelete:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: Removes audits from DynamoDB and S3
      Code: ../dist/Stream_Audits_Delete
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 5
      Role: !GetAtt RoleAudits.Arn
      Environment:
        Variables:
          AUDITS_BUCKET: !Ref BucketAudits
    DependsOn:
      - DynamoTableAudits

  DynamoTableAudits:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      StreamSpecification:
        StreamViewType: NEW_IMAGE
    DependsOn:
      - RoleAudits

  RoleAudits:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"

  ApiGatewayHttpApi:
    Type: "AWS::ApiGatewayV2::Api"
    Properties:
      Body:
        openapi: "3.0.1"
        info:
          title: "Audits API"
          version: "0.0.1"
        paths:
          /audits:
            get:
              responses:
                default:
                  description: "GET /audits"
              x-amazon-apigateway-integration:
                payloadFormatVersion: "2.0"
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaAPIAuditsIndex.Arn}/invocations
                connectionType: "INTERNET"
            post:
              responses:
                default:
                  description: "POST /audits"
              x-amazon-apigateway-integration:
                payloadFormatVersion: "2.0"
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaAPIAuditsCreate.Arn}/invocations
                connectionType: "INTERNET"
          /audits/{audit}:
            get:
              responses:
                default:
                  description: "GET /audits/{audit}"
              x-amazon-apigateway-integration:
                payloadFormatVersion: "2.0"
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaAPIAuditsShow.Arn}/invocations
                connectionType: "INTERNET"
        x-amazon-apigateway-cors:
          allowMethods:
            - "GET"
            - "HEAD"
            - "OPTIONS"
            - "POST"
          allowOrigins:
            - "*"

Outputs:
  HttpApiEndpoint:
    Description: The endpoint for the API
    Value: !GetAtt ApiGatewayHttpApi.ApiEndpoint
