name: Lint

on:
  pull_request:

jobs:
  js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ESLint
        uses: actions/setup-node@v2
        with:
          cache: "npm"
      - name: Install NPM dependencies
        run: npm ci
      - name: Run formatting && lint checks on JavaScript
        run: npm run check-format && npm run lint:js
  cloudformation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup CloudFormation Linter
        uses: scottbrenner/cfn-lint-action@v2
      - name: Run lint checks on CloudFormation
        run: npm run lint:cloudformation
